services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal

  app:
    image: sf-app:latest
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - ENV=production
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
    networks:
      - internal

  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
      - public

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
