services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: vla-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vla-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vla-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Application
      ENV: production
      PORT: 8080
      
      # Database
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_TLS: ${DB_TLS}
      
      # Redis
      REDIS_ADDR: redis:6379
      REDIS_PASS: ${REDIS_PASS}
      REDIS_DB: 0
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}

      # KYTAPAY
      KYTAPAY_BASE_URL: ${KYTAPAY_BASE_URL}
      KYTAPAY_CLIENT_ID: ${KYTAPAY_CLIENT_ID}
      KYTAPAY_CLIENT_SECRET: ${KYTAPAY_CLIENT_SECRET}
      CALLBACK_WITHDRAW: ${CALLBACK_WITHDRAW}
      NOTIFY_URL: ${NOTIFY_URL}
      SUCCESS_URL: ${SUCCESS_URL}
      FAILED_URL: ${FAILED_URL}

      # KLIKPAY
      KLIKPAY_BASE_URL: ${KLIKPAY_BASE_URL}
      KLIKPAY_CLIENT_ID: ${KLIKPAY_CLIENT_ID}
      KLIKPAY_CLIENT_SECRET: ${KLIKPAY_CLIENT_SECRET}

      # Cron
      CRON_KEY: ${CRON_KEY}
      SF_API_KEY: ${SF_API_KEY}
      
      # S3 (if using file uploads)
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}

      RATE_IP_DEFAULT: 200
      RATE_IP_AUTH: 10
      RATE_USER_AUTH: 10
      RATE_USER_API: 100
      RATE_USER_UPLOAD: 10
      RATE_USER_ADMIN: 500
      RATE_CLEANUP_SECONDS: 60
      
      TRUSTED_PROXIES: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: vla-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - app-network
    profiles:
      - nginx

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
